# These are supported funding model platforms

github: # [andipandi111, andrea mariadb, andrea-mariadb-2]
patreon: # andrea mareadb
open_collective: # andreamariadbandgeez
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.youtube.com/channel/UCuoDzKdqTwXtJe5kwo4tNYQ, https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg, https://www.youtube.com/channel/UC8HoS7gDQP-yIYQIlPLGeLw, https://www.youtube.com/channel/UCsxFFZcE80qFzuR262OFJHQ,']
.npm
.yml
.yaml
